steps:

  - label: 'Packager'
    key: "packager"
    timeout_in_minutes: 3
    plugins:
      - docker-compose#v3.7.0:
          build: packager
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/source-maps
          cache-from:  packager:855461928731.dkr.ecr.us-west-1.amazonaws.com/source-maps:packager-${BRANCH_NAME}
      - docker-compose#v3.7.0:
          push: packager:855461928731.dkr.ecr.us-west-1.amazonaws.com/source-maps:packager-${BRANCH_NAME}
      - docker-compose#v3.7.0:
          run: packager
    artifact_paths: build/bugsnag-source-maps.tgz

  - label: 'Run Maze Runner tests (browser)'
    key: "run-maze-browser"
    depends_on: "packager"
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.3.0:
          download: build/bugsnag-source-maps.tgz
      - docker-compose#v3.7.0:
          use-aliases: true
          run: maze-runner
          command: ["--fail-fast", "features/browser-upload-one.feature", "features/browser-upload-multiple.feature"]

  - label: 'Run Maze Runner tests (node)'
    key: "run-maze-node"
    depends_on: "packager"
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.3.0:
          download: build/bugsnag-source-maps.tgz
      - docker-compose#v3.7.0:
          use-aliases: true
          run: maze-runner
          command: ["--fail-fast", "features/node-upload-one.feature", "features/node-upload-multiple.feature"]

  - label: 'Run Maze Runner tests (react native)'
    key: "run-maze-react-native"
    depends_on: "packager"
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.3.0:
          download: build/bugsnag-source-maps.tgz
      - docker-compose#v3.7.0:
          use-aliases: true
          run: maze-runner
          command: ["--fail-fast", "features/react-native-upload-one.feature"]

  - label: 'Run Maze Runner tests (react native fetch)'
    key: "run-maze-react-native-fetch"
    depends_on: "packager"
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.3.0:
          download: build/bugsnag-source-maps.tgz
      - docker-compose#v3.7.0:
          use-aliases: true
          run: maze-runner
          command: ["--fail-fast", "features/react-native-fetch.feature"]

  #
  # License audit
  #
  - name: ':copyright: License Audit'
    plugins:
      docker-compose#v3.7.0:
        run: license_finder
    command: /bin/bash -lc '/scan/scripts/license_finder.sh'
